### ISSUE TITLE
Misspelling....

### ISSUE THREAD

**Issue by PySimpleGUI** [parsely1231/LC_Manager#14]
![image](https://user-images.githubusercontent.com/46163555/79157138-0dec8600-7da2-11ea-8d8f-df6896f9b5a2.png)

Should be PySimpleGUI :-)

I really like that you placed lots of screenshots in your readme.  It immediately gets the attention of visitors and they're more likely to check your project out further.  I also like the badges you used with the version numbers.  Very nicely polished project as a result.  Congrats on a job well done.

**Comment by parsely1231** [comment]
Thanks for pointing out my mistake. I've fixed it.
I'm sorry for misspelling your precious name.
Your GUI package is great and very easy to use, even for me as a beginner.
Thank you for your great job!!!

**Comment by PySimpleGUI** [comment]
> I'm sorry for misspelling your precious name.

"precious name"  HA!

I  was more interested in thanking you for posting screenshots, something often missing from GitHub projects.   Thanking you for the images was more important than name spelling.
